language: node_js
node_js: "8"
cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli
  - gulp -v
script:
  - NODE_ENV=production gulp build

after_success:
  - MOCHA_BADGE_GEN_OUTPUT=./build/unit-badge.svg npm run test
  - npm run coveralls
  
deploy:
  provider: pages
  local_dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master